version: '3.8'

services:
    app:
        build: .
        environment: 
            DATIC_URL: "http://datic:8080/datic/api/auth"
        depends_on: 
            - datic
        ports: 
            - "3000:3000"
    
    datic: 
        image: estalvgs/datic